from __future__ import annotations

from datetime import datetime

from oracle_adw_snapshotter.storage.snapshot_reader import SnapshotReader


class SchedulerRunRepository:
    schedule_runs_table = "SNAPSHOT_SCHEDULE_RUNS"
    schedule_log_table = "SNAPSHOT_SCHEDULE_LOGS"

    def ensure_tables(self, connection) -> None:
        cursor = connection.cursor()
        try:
            self._ensure_table(
                cursor,
                self.schedule_runs_table,
                f"""
                CREATE TABLE {self.schedule_runs_table} (
                    SCHEDULE_RUN_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    SCHEDULE_NAME VARCHAR2(200) NOT NULL,
                    PLANNED_AT_UTC TIMESTAMP WITH TIME ZONE NOT NULL,
                    STARTED_AT_UTC TIMESTAMP WITH TIME ZONE,
                    FINISHED_AT_UTC TIMESTAMP WITH TIME ZONE,
                    RANDOM_VALUE NUMBER(3),
                    STATUS VARCHAR2(50) NOT NULL,
                    SUCCESS_FLAG CHAR(1) CHECK (SUCCESS_FLAG IN ('Y', 'N')),
                    READ_COUNT NUMBER,
                    WROTE_COUNT NUMBER,
                    SUMMARY VARCHAR2(2000),
                    ERROR_MESSAGE CLOB,
                    CREATED_AT_UTC TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
                )
                """,
            )
            self._ensure_table(
                cursor,
                self.schedule_log_table,
                f"""
                CREATE TABLE {self.schedule_log_table} (
                    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    SCHEDULE_RUN_ID NUMBER,
                    SCHEDULE_NAME VARCHAR2(200) NOT NULL,
                    PLANNED_AT_UTC TIMESTAMP WITH TIME ZONE NOT NULL,
                    ACTUAL_AT_UTC TIMESTAMP WITH TIME ZONE NOT NULL,
                    RANDOM_VALUE NUMBER(3) NOT NULL,
                    READ_SOURCE_TABLE VARCHAR2(200),
                    READ_ROW_COUNT NUMBER,
                    READ_SUMMARY VARCHAR2(2000),
                    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON),
                    CREATED_AT_UTC TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
                )
                """,
            )
        finally:
            cursor.close()

    def insert_started(
        self,
        connection,
        *,
        schedule_name: str,
        planned_at_utc: datetime,
        started_at_utc: datetime,
        random_value: int,
    ) -> int | None:
        self.ensure_tables(connection)
        cursor = connection.cursor()
        try:
            run_id_var = cursor.var(int)
            cursor.execute(
                f"""
                INSERT INTO {self.schedule_runs_table} (
                    SCHEDULE_NAME,
                    PLANNED_AT_UTC,
                    STARTED_AT_UTC,
                    RANDOM_VALUE,
                    STATUS
                ) VALUES (
                    :schedule_name,
                    :planned_at_utc,
                    :started_at_utc,
                    :random_value,
                    :status
                ) RETURNING SCHEDULE_RUN_ID INTO :schedule_run_id
                """,
                schedule_name=schedule_name,
                planned_at_utc=planned_at_utc,
                started_at_utc=started_at_utc,
                random_value=random_value,
                status="RUNNING",
                schedule_run_id=run_id_var,
            )
            value = run_id_var.getvalue()
            return int(value[0]) if value else None
        finally:
            cursor.close()

    def insert_log_entry(
        self,
        connection,
        *,
        schedule_run_id: int | None,
        schedule_name: str,
        planned_at_utc: datetime,
        started_at_utc: datetime,
        random_value: int,
        read_source_table: str,
        read_row_count: int,
        read_summary: str,
        payload_json: str,
    ) -> None:
        self.ensure_tables(connection)
        cursor = connection.cursor()
        try:
            cursor.execute(
                f"""
                INSERT INTO {self.schedule_log_table} (
                    SCHEDULE_RUN_ID,
                    SCHEDULE_NAME,
                    PLANNED_AT_UTC,
                    ACTUAL_AT_UTC,
                    RANDOM_VALUE,
                    READ_SOURCE_TABLE,
                    READ_ROW_COUNT,
                    READ_SUMMARY,
                    PAYLOAD_JSON
                ) VALUES (
                    :schedule_run_id,
                    :schedule_name,
                    :planned_at_utc,
                    :actual_at_utc,
                    :random_value,
                    :read_source_table,
                    :read_row_count,
                    :read_summary,
                    :payload_json
                )
                """,
                schedule_run_id=schedule_run_id,
                schedule_name=schedule_name,
                planned_at_utc=planned_at_utc,
                actual_at_utc=started_at_utc,
                random_value=random_value,
                read_source_table=read_source_table,
                read_row_count=read_row_count,
                read_summary=read_summary,
                payload_json=payload_json,
            )
        finally:
            cursor.close()

    def mark_finished(
        self,
        connection,
        *,
        schedule_run_id: int | None,
        finished_at_utc: datetime,
        status: str,
        success: bool,
        summary: str,
        read_count: int | None = None,
        wrote_count: int | None = None,
        error_message: str | None = None,
    ) -> None:
        if schedule_run_id is None:
            return
        cursor = connection.cursor()
        try:
            cursor.execute(
                f"""
                UPDATE {self.schedule_runs_table}
                SET FINISHED_AT_UTC = :finished_at_utc,
                    STATUS = :status,
                    SUCCESS_FLAG = :success_flag,
                    READ_COUNT = :read_count,
                    WROTE_COUNT = :wrote_count,
                    SUMMARY = :summary,
                    ERROR_MESSAGE = :error_message
                WHERE SCHEDULE_RUN_ID = :schedule_run_id
                """,
                finished_at_utc=finished_at_utc,
                status=status,
                success_flag="Y" if success else "N",
                read_count=read_count,
                wrote_count=wrote_count,
                summary=summary,
                error_message=error_message,
                schedule_run_id=schedule_run_id,
            )
        finally:
            cursor.close()

    @staticmethod
    def safe_fetch_preview(connection, reader: SnapshotReader, table_name: str, limit: int):
        try:
            return reader.fetch_latest_rows(connection=connection, table_name=table_name, limit=limit)
        except Exception:
            return []

    @staticmethod
    def _ensure_table(cursor, table_name: str, create_sql: str) -> None:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM user_tables
            WHERE table_name = :table_name
            """,
            table_name=table_name.upper(),
        )
        exists = cursor.fetchone()[0] > 0
        if not exists:
            cursor.execute(create_sql)
