from __future__ import annotations

import json
from typing import Any

from oracle_adw_snapshotter.models.types import SnapshotBatch


class SnapshotWriter:
    def ensure_table(self, connection, table_name: str) -> None:
        cursor = connection.cursor()
        try:
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM user_tables
                WHERE table_name = :table_name
                """,
                table_name=table_name.upper(),
            )
            exists = cursor.fetchone()[0] > 0
            if exists:
                return

            cursor.execute(
                f"""
                CREATE TABLE {table_name} (
                    SNAPSHOT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    JOB_NAME VARCHAR2(200) NOT NULL,
                    COLLECTED_AT_UTC TIMESTAMP WITH TIME ZONE NOT NULL,
                    SOURCE_SQL CLOB,
                    PAYLOAD_JSON CLOB CHECK (PAYLOAD_JSON IS JSON)
                )
                """
            )
        finally:
            cursor.close()

    def write_batch(self, connection, batch: SnapshotBatch) -> int:
        self.ensure_table(connection, batch.target_table)
        cursor = connection.cursor()
        try:
            payload_rows = [
                {
                    **self._normalize_row(row),
                    "_snapshot_job_name": batch.job_name,
                    "_snapshot_collected_at_utc": batch.collected_at.isoformat(),
                }
                for row in batch.rows
            ]
            cursor.executemany(
                f"""
                INSERT INTO {batch.target_table} (
                    JOB_NAME,
                    COLLECTED_AT_UTC,
                    SOURCE_SQL,
                    PAYLOAD_JSON
                ) VALUES (
                    :job_name,
                    :collected_at_utc,
                    :source_sql,
                    :payload_json
                )
                """,
                [
                    {
                        "job_name": batch.job_name,
                        "collected_at_utc": batch.collected_at,
                        "source_sql": batch.source_sql,
                        "payload_json": json.dumps(row, default=str, ensure_ascii=False),
                    }
                    for row in payload_rows
                ],
            )
            return len(payload_rows)
        finally:
            cursor.close()

    @staticmethod
    def _normalize_row(row: dict[str, Any]) -> dict[str, Any]:
        return {key: value for key, value in row.items()}
